name: twitter_login
description: Flutter Twitter Login Plugin. Library for login with Twitter APIs OAuth service
version: 3.0.7
homepage: https://twitter.com/0maru_dev
repository: https://github.com/0maru/twitter_login

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.5
  http: ^0.12.2
  flutter_inappwebview: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.maru.twitter_login
        pluginClass: TwitterLoginPlugin
      ios:
        pluginClass: TwitterLoginPlugin
